In [4]:
2+2

4

In [3]:
print("Helo, Jupyter!")

Helo, Jupyter!


# NumPy

## - массивы

In [5]:
# иьпорт библеотеки NumPy и даем ему псевдоним
import numpy as np

In [7]:
#!pip install numpy

In [10]:
# создангие списка
my_list = [1,2,3,4]
my_list 

[1, 2, 3, 4]

In [11]:
# создание одномерного массива (вектора)
np.array(my_list)

array([1, 2, 3, 4])

In [12]:
# создание массива из нулей
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# атрибут, показывающий тип значенний массива
z.dtype

dtype('float64')

In [14]:
# создание массива из 8мибитных целых значений
np.zeros(10, dtype="int8")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [15]:
np.zeros(10, dtype="int").dtype

dtype('int32')

In [16]:
# создание 2мерного массива из нулей

# форма в виде картежа (или списка)
# (количество строк, количество столбцов)
shape =(3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])